# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

workspace 'Fend App'

target 'Fend App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fend App
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
end
